// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: internal/extension/proto/extension_context.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ObjectReference is the K8s API object referenced in an HTTPRouteFilter extensionRef.
// The API object must be valid within the cluster and the Group and Kind must be
// registered with the cluster.
//
// TODO: Gateway API currently doesn't allow setting a version...this is probably due to
// the assumption that it is an internal implementation detail and should be resolved
// be the implementation (complete guess or maybe we need to ask for the enhancement???)
type ObjectReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// api_group is an K8s group of the referent (e.g gateway.networking.k8s.io).
	ApiGroup string `protobuf:"bytes,1,opt,name=api_group,json=apiGroup,proto3" json:"api_group,omitempty"`
	// kind is the Kind of the referent (e.g HTTPRoute, Service).
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// name is the object name of the referent.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ObjectReference) Reset() {
	*x = ObjectReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_extension_proto_extension_context_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectReference) ProtoMessage() {}

func (x *ObjectReference) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extension_proto_extension_context_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectReference.ProtoReflect.Descriptor instead.
func (*ObjectReference) Descriptor() ([]byte, []int) {
	return file_internal_extension_proto_extension_context_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectReference) GetApiGroup() string {
	if x != nil {
		return x.ApiGroup
	}
	return ""
}

func (x *ObjectReference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ObjectReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// HTTPListenerExtensionContext provides context on
// the users intent so that the provided XDS can be modified by the Extension.
type HTTPListenerExtensionContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// route_filter_extension_ctxs provides a list of HTTPRouteFilters
	// that use an extensionRef registered by the extension.
	// The list is in the order it was processed in XDS Translation
	RouteFilterExtensionCtxs []*HTTPRouteFilterExtensionContext `protobuf:"bytes,1,rep,name=route_filter_extension_ctxs,json=routeFilterExtensionCtxs,proto3" json:"route_filter_extension_ctxs,omitempty"`
}

func (x *HTTPListenerExtensionContext) Reset() {
	*x = HTTPListenerExtensionContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_extension_proto_extension_context_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPListenerExtensionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPListenerExtensionContext) ProtoMessage() {}

func (x *HTTPListenerExtensionContext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extension_proto_extension_context_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPListenerExtensionContext.ProtoReflect.Descriptor instead.
func (*HTTPListenerExtensionContext) Descriptor() ([]byte, []int) {
	return file_internal_extension_proto_extension_context_proto_rawDescGZIP(), []int{1}
}

func (x *HTTPListenerExtensionContext) GetRouteFilterExtensionCtxs() []*HTTPRouteFilterExtensionContext {
	if x != nil {
		return x.RouteFilterExtensionCtxs
	}
	return nil
}

// HTTPRouteFilterExtensionContext provides context about an HTTPRoute containing an
// ExtensionRef HTTPRouteFilterType. The context provided includes which filterchain/s,
// route and Group/Kind of the object referent.
type HTTPRouteFilterExtensionContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// route_name is the name of HTTPRoute the filter is being applied on
	//
	// TODO: Will we need more context than just route name such as Path, Headers,
	// and QueryParameter matches?
	RouteName string `protobuf:"bytes,1,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	// hostnames are the fully qualified domain names attached to the HTTPRoute
	Hostnames []string `protobuf:"bytes,2,rep,name=hostnames,proto3" json:"hostnames,omitempty"`
	// route_filter_extension_refs contains the list of Objects added as extensionRefs
	// to an HTTPRouteFilter.
	RouteFilterExtensionRefs []*ObjectReference `protobuf:"bytes,3,rep,name=route_filter_extension_refs,json=routeFilterExtensionRefs,proto3" json:"route_filter_extension_refs,omitempty"`
}

func (x *HTTPRouteFilterExtensionContext) Reset() {
	*x = HTTPRouteFilterExtensionContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_extension_proto_extension_context_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPRouteFilterExtensionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRouteFilterExtensionContext) ProtoMessage() {}

func (x *HTTPRouteFilterExtensionContext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extension_proto_extension_context_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRouteFilterExtensionContext.ProtoReflect.Descriptor instead.
func (*HTTPRouteFilterExtensionContext) Descriptor() ([]byte, []int) {
	return file_internal_extension_proto_extension_context_proto_rawDescGZIP(), []int{2}
}

func (x *HTTPRouteFilterExtensionContext) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *HTTPRouteFilterExtensionContext) GetHostnames() []string {
	if x != nil {
		return x.Hostnames
	}
	return nil
}

func (x *HTTPRouteFilterExtensionContext) GetRouteFilterExtensionRefs() []*ObjectReference {
	if x != nil {
		return x.RouteFilterExtensionRefs
	}
	return nil
}

var File_internal_extension_proto_extension_context_proto protoreflect.FileDescriptor

var file_internal_extension_proto_extension_context_proto_rawDesc = []byte{
	0x0a, 0x30, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x16, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x56, 0x0a, 0x0f, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x61, 0x70, 0x69, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x96, 0x01, 0x0a, 0x1c, 0x48, 0x54, 0x54, 0x50, 0x4c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x76, 0x0a, 0x1b, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x74,
	0x78, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x52, 0x18, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x78,
	0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x74, 0x78, 0x73, 0x22, 0xc6, 0x01, 0x0a, 0x1f,
	0x48, 0x54, 0x54, 0x50, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45,
	0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x66, 0x0a, 0x1b,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x65, 0x78, 0x74,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x66, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x18, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x66, 0x73, 0x42, 0x1a, 0x5a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_extension_proto_extension_context_proto_rawDescOnce sync.Once
	file_internal_extension_proto_extension_context_proto_rawDescData = file_internal_extension_proto_extension_context_proto_rawDesc
)

func file_internal_extension_proto_extension_context_proto_rawDescGZIP() []byte {
	file_internal_extension_proto_extension_context_proto_rawDescOnce.Do(func() {
		file_internal_extension_proto_extension_context_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_extension_proto_extension_context_proto_rawDescData)
	})
	return file_internal_extension_proto_extension_context_proto_rawDescData
}

var file_internal_extension_proto_extension_context_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_extension_proto_extension_context_proto_goTypes = []interface{}{
	(*ObjectReference)(nil),                 // 0: envoygateway.extension.ObjectReference
	(*HTTPListenerExtensionContext)(nil),    // 1: envoygateway.extension.HTTPListenerExtensionContext
	(*HTTPRouteFilterExtensionContext)(nil), // 2: envoygateway.extension.HTTPRouteFilterExtensionContext
}
var file_internal_extension_proto_extension_context_proto_depIdxs = []int32{
	2, // 0: envoygateway.extension.HTTPListenerExtensionContext.route_filter_extension_ctxs:type_name -> envoygateway.extension.HTTPRouteFilterExtensionContext
	0, // 1: envoygateway.extension.HTTPRouteFilterExtensionContext.route_filter_extension_refs:type_name -> envoygateway.extension.ObjectReference
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_extension_proto_extension_context_proto_init() }
func file_internal_extension_proto_extension_context_proto_init() {
	if File_internal_extension_proto_extension_context_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_extension_proto_extension_context_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_extension_proto_extension_context_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTPListenerExtensionContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_extension_proto_extension_context_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTPRouteFilterExtensionContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_extension_proto_extension_context_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_extension_proto_extension_context_proto_goTypes,
		DependencyIndexes: file_internal_extension_proto_extension_context_proto_depIdxs,
		MessageInfos:      file_internal_extension_proto_extension_context_proto_msgTypes,
	}.Build()
	File_internal_extension_proto_extension_context_proto = out.File
	file_internal_extension_proto_extension_context_proto_rawDesc = nil
	file_internal_extension_proto_extension_context_proto_goTypes = nil
	file_internal_extension_proto_extension_context_proto_depIdxs = nil
}
